// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProject.DAL.Contexts;

namespace Backend_miniproject.Migrations
{
    [DbContext(typeof(MiniProjectContext))]
    [Migration("20230625132515_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Backend_miniproject.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Backend_miniproject.Model.SocialAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Person_id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("SocialAccounts");
                });

            modelBuilder.Entity("Backend_miniproject.Model.SocialSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Person_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("SocialSkills");
                });

            modelBuilder.Entity("Backend_miniproject.Model.SocialAccounts", b =>
                {
                    b.HasOne("Backend_miniproject.Model.Person", null)
                        .WithMany("SocialAccounts")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Backend_miniproject.Model.SocialSkills", b =>
                {
                    b.HasOne("Backend_miniproject.Model.Person", null)
                        .WithMany("SocialSkills")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Backend_miniproject.Model.Person", b =>
                {
                    b.Navigation("SocialAccounts");

                    b.Navigation("SocialSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
